export const fashionPortrait = {
  slug: "fashion-portrait",
  name: "时尚人像",
  description: "专业时尚人像写真，支持上传人脸参考图，可调光线、背景、姿态、妆容和服装风格。",
  category: "fashion" as const,
  tags: ["时尚", "人像", "写真", "换脸"],
  thumbnail_url: null,
  thumbnail_path: null,
  default_model: "nano-banana-2" as const,
  compatible_models: ["nano-banana-2", "nano-banana-pro-4k", "nano-banana-pro-2k"] as const,
  default_image_size: { width: 1024, height: 1536 },
  variables: [
    {
      id: "face_ref",
      name: "人物五官照片",
      type: "image" as const,
      required: true,
      priority: 0,
      accept: "image/jpeg,image/png,image/webp",
      maxSizeMB: 10,
      uploadHint: "请上传一张清晰的正面人脸照片，确保五官清晰可见、光线均匀",
    },
    {
      id: "lighting",
      name: "光线",
      type: "select" as const,
      required: true,
      priority: 1,
      options: [
        { value: "soft-natural", label: "柔和自然光", description: "窗光/阴天漫射光，皮肤质感细腻" },
        { value: "golden-hour", label: "黄金时段", description: "日落侧光，暖调高级感" },
        { value: "studio-rim", label: "棚拍轮廓光", description: "硬光勾边，时尚杂志感" },
        { value: "neon-color", label: "霓虹彩光", description: "粉蓝紫混合光，赛博朋克氛围" },
      ],
      defaultValue: "soft-natural",
    },
    {
      id: "background",
      name: "背景",
      type: "select" as const,
      required: true,
      priority: 2,
      options: [
        { value: "clean-studio", label: "纯色棚景", description: "白/灰/黑纯色背景" },
        { value: "urban-street", label: "城市街头", description: "街道、涂鸦墙、霓虹招牌" },
        { value: "nature-outdoor", label: "自然户外", description: "花田、森林、海边" },
        { value: "luxury-interior", label: "奢华室内", description: "酒店大堂、艺术馆、高级餐厅" },
      ],
      defaultValue: "clean-studio",
    },
    {
      id: "pose",
      name: "姿态",
      type: "select" as const,
      required: true,
      priority: 3,
      options: [
        { value: "standing-confident", label: "站立自信", description: "正面/微侧站姿，目视镜头" },
        { value: "sitting-relaxed", label: "坐姿随性", description: "椅子/台阶/地面坐姿" },
        { value: "walking-dynamic", label: "行走动态", description: "迈步/回眸/风吹效果" },
        { value: "closeup-portrait", label: "半身特写", description: "胸部以上近景，强调五官" },
      ],
      defaultValue: "standing-confident",
    },
    {
      id: "makeup",
      name: "妆容",
      type: "select" as const,
      required: false,
      priority: 4,
      options: [
        { value: "natural-fresh", label: "清透裸妆" },
        { value: "editorial-bold", label: "浓郁杂志妆" },
        { value: "smoky-evening", label: "烟熏晚宴妆" },
      ],
      defaultValue: "natural-fresh",
    },
    {
      id: "outfit",
      name: "服装风格",
      type: "select" as const,
      required: false,
      priority: 5,
      options: [
        { value: "casual-streetwear", label: "休闲街头" },
        { value: "formal-tailoring", label: "正式剪裁" },
        { value: "haute-couture", label: "高定礼服" },
        { value: "athleisure", label: "运动休闲" },
      ],
      defaultValue: "casual-streetwear",
    },
  ],
  skill_prompt:
    "You are a world-class fashion photographer. Generate a professional fashion portrait with magazine-quality composition, precise skin texture rendering, and cinematic color grading. Maintain the subject's exact facial features from the reference image. Ensure editorial-level styling, natural body proportions, and high-end retouching aesthetic.",
  base_prompt:
    "A professional fashion portrait with {{lighting}} lighting, set against a {{background}} scene. The subject is in a {{pose}} pose, with {{makeup}} makeup style, wearing {{outfit}} attire. Ultra-high detail, 8K quality, fashion magazine editorial look.",
  negative_prompt:
    "deformed face, distorted features, extra limbs, bad anatomy, blurry, low quality, text, watermark, logo, oversaturated, plastic skin, uncanny valley",
  credit_multiplier: 1.5,
  is_published: true,
  sort_order: 1,
  tier_required: "free" as const,
};
