export const outfitTryon = {
  slug: "outfit-tryon",
  name: "AI 换装",
  description: "上传人物照片和服装图片，AI 自动换装生成效果图。",
  category: "fashion" as const,
  tags: ["换装", "试衣", "电商"],
  thumbnail_url: null,
  thumbnail_path: null,
  default_model: "nano-banana-pro-4k" as const,
  compatible_models: ["nano-banana-pro-4k", "nano-banana-pro-2k"] as const,
  default_image_size: { width: 1024, height: 1536 },
  variables: [
    {
      id: "face_ref",
      name: "人物五官照片",
      type: "image" as const,
      required: true,
      priority: 0,
      accept: "image/jpeg,image/png,image/webp",
      maxSizeMB: 10,
      uploadHint: "请上传一张清晰正面人脸照片",
    },
    {
      id: "outfit_ref",
      name: "服装参考图",
      type: "image" as const,
      required: true,
      priority: 1,
      accept: "image/jpeg,image/png,image/webp",
      maxSizeMB: 10,
      uploadHint: "请上传想要试穿的服装图片（平铺或模特图均可）",
    },
    {
      id: "scene",
      name: "场景",
      type: "select" as const,
      required: true,
      priority: 2,
      options: [
        { value: "studio-white", label: "白色棚景" },
        { value: "outdoor-casual", label: "户外街拍" },
        { value: "indoor-luxury", label: "室内精致" },
      ],
      defaultValue: "studio-white",
    },
    {
      id: "body_pose",
      name: "姿态",
      type: "select" as const,
      required: false,
      priority: 3,
      options: [
        { value: "front-standing", label: "正面站立" },
        { value: "slight-turn", label: "微侧转身" },
        { value: "walking", label: "行走动态" },
      ],
      defaultValue: "front-standing",
    },
  ],
  skill_prompt:
    "You are an expert virtual try-on AI. Perfectly transfer the clothing from the outfit reference image onto the person from the face reference image. Maintain exact facial features, natural body proportions, and realistic fabric draping. The result should look like a genuine photograph, not a composite.",
  base_prompt:
    "A photorealistic full-body shot in a {{scene}} environment, with the subject in a {{body_pose}} pose, wearing the exact outfit from the reference image. Professional e-commerce photography quality, natural lighting, crisp details.",
  negative_prompt:
    "deformed, distorted clothing, wrong proportions, blurry, low quality, text, watermark, floating garments, mismatched style",
  credit_multiplier: 2.0,
  is_published: true,
  sort_order: 2,
  tier_required: "free" as const,
};
